spring:
  rabbitmq:
    host: rabbit
  cloud:
    consul:
      host: consul-server

  datasource:
    url: jdbc:mysql://facture-db:3306/factureDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
