spring:
  cloud:
    consul:
      host: localhost

app:
  services:
    facture:
      url: http://localhost:8282/factures
      name: facture
    reservation:
      url: http://localhost:8181/reserv
      name: reservation