spring:
  application:
    name: api-gateway
  profiles:
    active: prod
  cloud:
    consul:
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
        service-name: ${spring.application.name}
        health-check-path: "/health"