spring:
  application:
    name: reservation-service

  profiles:
    active: prod

  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
        service-name: ${spring.application.name}
        health-check-path: "/health"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
