spring:
  rabbitmq:
    host: rabbit

  cloud:
    consul:
      host: consul-server

  datasource:
    url: jdbc:mysql://reserv-db:3306/reservDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass